
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='unrest_framework',
    version='0.1.0',
    python_requires='==3.*,>=3.6.0',
    author='ph',
    author_email='robotnaoborot@gmail.com',
    license='MIT',
    packages=['unrest_framework'],
    package_dir={"": "."},
    package_data={"unrest_framework": ["templates/*"]},
    install_requires=['django-filters==0.*,>=0.2.1', 'djangorestframework==3.*,>=3.10.0', 'jinja2==2.*,>=2.10.0'],
)
